version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
  reviewers:
  - nwtgck
  assignees:
  - nwtgck
  ignore:
  - dependency-name: "@types/node"
    versions:
    - ">= 13.a, < 14"
  - dependency-name: fp-ts
    versions:
    - 2.10.0
    - 2.10.1
    - 2.10.4
    - 2.9.3
    - 2.9.4
    - 2.9.5
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@types/mocha"
    versions:
    - 8.2.1
  - dependency-name: js-yaml
    versions:
    - 4.0.0
  - dependency-name: io-ts
    versions:
    - 2.2.13
    - 2.2.14
    - 2.2.15
  - dependency-name: "@types/yargs"
    versions:
    - 16.0.0
  - dependency-name: piping-server
    versions:
    - 1.1.4
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
  reviewers:
  - nwtgck
  assignees:
  - nwtgck
  ignore:
  - dependency-name: node
    versions:
    - ">= 13.a, < 14"
  - dependency-name: node
    versions:
    - ">= 15.a, < 16"
  - dependency-name: node
    versions:
    - 14.16.0.pre.alpine
